### ISSUE TITLE
Data input

### ISSUE THREAD

**Issue by AmadeusW** [jefking/BIGdata#1]
Create a front end component that allows users to type text. It intercepts the following data:
- What character was pressed
- Time of the character press
- ID of the user that pressed the key*
- _add more..._

**Comment by jefking** [comment]
http://fabriccontroller.net/blog/posts/iot-with-azure-service-bus-event-hubs-authenticating-and-sending-from-any-type-of-device-net-and-js-samples/

**Comment by jefking** [comment]
https://github.com/jefking/BIGdata/blob/master/doc/JSConnection.txt

**Comment by jlVidal** [comment]
My first idea of the scheme /structure of the data:
- Is the first key pressed after focus on text box
- Guid of typing // each begin/end of typing will have a Guid
- Order number // order of the key-press of keyboard/screen event (like first key, second....)
- Key down time // date time key-down event
- Key up time // date time key-up event
- Key value // key value
- Is the last key pressed after unfocused on text box 
- Lost focus time 

Please feel free to suggest/add remove fields

**Comment by jefking** [comment]
Loging Buffer = 50-100 keystrokes.

**Comment by jlVidal** [comment]
Sample of the data that is currently being sent by sampleStrokes project:

{
    "userId": "1",
    "strokes": [
        {
            "time": "2015-04-19T01:03:33.170Z",
            "order": 7,
            "action": 3,
            "guid": "6d4ccf2b-e48b-6eb8-21f0-5396f7cacbca",
            "value": "S"
        },
        {
            "time": "2015-04-19T01:03:33.260Z",
            "order": 8,
            "action": 4,
            "guid": "6d4ccf2b-e48b-6eb8-21f0-5396f7cacbca",
            "value": "A"
        },
        {
            "time": "2015-04-19T01:03:33.300Z",
            "order": 9,
            "action": 3,
            "guid": "6d4ccf2b-e48b-6eb8-21f0-5396f7cacbca",
            "value": "D"
        }
    ]
}

FIELD LEGEND:

"guid" = Each begin/end generate a different Guidtype
"action" = 
1 FocusIn
2 FocusOut
3 KeyDown
4 KeyUp

**Comment by dstjean** [comment]
Here's the new data format
{
 user_id: GUID
 key_up_time: Time in ms,
 key_down_time: Time in ms,
 keystroke: Character
}
